<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Try-catch()  对于流的新用法(try-with-resources，try后加括号 ), 以及异常新方法addSuppressed(针对异常屏蔽) - 编程鬼谷子的博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="Try-catch()  对于流的新用法(try-with-resources，try后加括号 ), 以及异常新方法addSuppressed(针对异常屏蔽)" />
<meta property="og:description" content="Java7 开始 ，针对stream流的close()操作有了新的写法。
之前我们都要在finally中执行close()方法，如果用到了多个流，要写不少的多余代码，finally中全是close()，而且我们的写法还不一定安全（大佬可能会避免）。如下代码：
首先贴上我的两个自定义流：
class MyFileOutputStream extends FileOutputStream { MyFileOutputStream(String name) throws FileNotFoundException { super(name); } @Override public void close() throws IOException { System.out.println(&#34;&gt;&gt;&gt;&gt;MyFileOutputStream close&#34;); throw new IOException(&#34;Exception in MyFileOutputStream close()&#34;); } public void read() { System.out.println(&#34;&gt;&gt;&gt;&gt;MyFileOutputStream read&#34;); } } class MyZipOutputStream extends ZipOutputStream { public MyZipOutputStream(OutputStream out) { super(out); } @Override public void close() { System.out.println(&#34;&gt;&gt;&gt;&gt;MyZipOutputStream close&#34;); } public void read() throws IOException { System.out.println(&#34;&gt;&gt;&gt;&gt;MyZipOutputStream read&#34;); throw new IOException(&#34;" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://bcguiguzi.github.io/posts/54c70182834c699815cfeac4244ec6aa/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2019-08-27T17:49:48+08:00" />
<meta property="article:modified_time" content="2019-08-27T17:49:48+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程鬼谷子的博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程鬼谷子的博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">Try-catch()  对于流的新用法(try-with-resources，try后加括号 ), 以及异常新方法addSuppressed(针对异常屏蔽)</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="markdown_views prism-atom-one-light">
                    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                        <path stroke-linecap="round" d="M5,0 0,2.5 5,5z" id="raphael-marker-block" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></path>
                    </svg>
                    <p>Java7 开始 ，针对stream流的<code>close()</code>操作有了新的写法。<br> 之前我们都要在finally中执行<code>close()</code>方法，如果用到了多个流，要写不少的多余代码，<code>finally</code>中全是<code>close()</code>，而且我们的写法还不一定安全（大佬可能会避免）。如下代码：<br> <strong>首先贴上我的两个自定义流：</strong></p> 
<pre><code>class MyFileOutputStream extends FileOutputStream {

    MyFileOutputStream(String name) throws FileNotFoundException {
        super(name);
    }

    @Override
    public void close() throws IOException {
        System.out.println("&gt;&gt;&gt;&gt;MyFileOutputStream close");
        throw new IOException("Exception in MyFileOutputStream close()");
    }

    public void read() {
        System.out.println("&gt;&gt;&gt;&gt;MyFileOutputStream read");
    }

}

class MyZipOutputStream extends ZipOutputStream {

    public MyZipOutputStream(OutputStream out) {
        super(out);
    }
    
    @Override
    public void close() {
        System.out.println("&gt;&gt;&gt;&gt;MyZipOutputStream close");
    }

    public void read() throws IOException {
        System.out.println("&gt;&gt;&gt;&gt;MyZipOutputStream read");
        throw new IOException("Exception in MyZipOutputStream read()");
    }
}
</code></pre> 
<p><strong>关闭流的测试方法：</strong></p> 
<pre><code>public static void test() throws Exception {
        MyFileOutputStream file = null;
        MyZipOutputStream out = null;
        try {
            file = new MyFileOutputStream("E:\\ppp.txt");
            out = new MyZipOutputStream(file);
            out.read();
        } catch (Exception e) {
            System.out.println("MyZipOutputStream read error");
            throw new BaseException(e);
        } finally {
            if (null != file) {
                file.close();
            }
            if (null != out) {
                out.close();
            }
        }
    }
</code></pre> 
<p><strong>main方法：</strong></p> 
<pre><code>		try {
            test();
        } catch (Exception e) {
            e.printStackTrace();
        }
</code></pre> 
<p>执行结果：（注意：<code>file.close();</code>是发生了异常的）<br> <img src="https://images2.imgbox.com/05/dc/BBNX72ne_o.png" alt="在这里插入图片描述"><br> 可以看到，zip流并没有被关闭，因为在finally中<code>file.close()</code>发生了异常，导致后边的<code>out.close()</code> 没有执行。所以我们大部分的写法是有隐患的，并不完全正确。</p> 
<p><strong>下面采用<code>try-with-resources</code>的新写法：</strong></p> 
<pre><code>try (MyFileOutputStream file = new MyFileOutputStream("E:\\ppp.txt");
             MyZipOutputStream o = new MyZipOutputStream(file)
        ) {
            o.read();
        } catch (Exception e) {
            System.out.println("read  catch");
            e.printStackTrace();
        }
</code></pre> 
<p>新写法的结果：<br> <img src="https://images2.imgbox.com/c7/2d/ncFbufzk_o.png" alt="在这里插入图片描述"><br> 可以看到，即使发生异常，在<code>cache</code>前对这种方式对两个流都进行了关闭，而且写法简单，代码简洁又安全。看下编译后的class文件：</p> 
<pre><code>try {
            MyFileOutputStream file = new MyFileOutputStream("E:\\ppp.txt");
            Throwable var3 = null;

            try {
                MyZipOutputStream o = new MyZipOutputStream(file);
                Throwable var5 = null;

                try {
                    o.read();
                } catch (Throwable var30) {
                    var5 = var30;
                    throw var30;
                } finally {
                    if (o != null) {
                        if (var5 != null) {
                            try {
                                o.close();
                            } catch (Throwable var29) {
                                var5.addSuppressed(var29);
                            }
                        } else {
                            o.close();
                        }
                    }

                }
            } catch (Throwable var32) {
                var3 = var32;
                throw var32;
            } finally {
                if (file != null) {
                    if (var3 != null) {
                        try {
                            file.close();
                        } catch (Throwable var28) {
                            var3.addSuppressed(var28);
                        }
                    } else {
                        file.close();
                    }
                }

            }
        } catch (Exception var34) {
            System.out.println("read  catch");
            var34.printStackTrace();
        }
</code></pre> 
<p>Java替我们生成了安全的写法(应该也是大佬的写法)，不用我们去费功夫了。该语法会自动对实现了<code>AutoCloseable(Java7)</code>接口的类进行关闭，而原来的<code>Closeable</code>继承了该接口。</p> 
<p>**这里还有一个点，**第一个旧的打印结果中，明明<code>read</code>方法也发生了异常，但是最后抛出的异常只有<code>close</code>，这就是异常屏蔽。但是新的结果打印了两个异常，请注意这个词：<code>Suppressed:</code>，这个就是Java7 新增的修复异常屏蔽的方法，就是<code>Throwable.addSuppressed()</code> 方法，看编译后的class文件，就用到了这个写法，就是把捕获的异常加到异常列表中，具体可以看源码：</p> 
<pre><code>private List&lt;Throwable&gt; suppressedExceptions = SUPPRESSED_SENTINEL;

public final synchronized void addSuppressed(Throwable exception) {
        if (exception == this)
            throw new IllegalArgumentException(SELF_SUPPRESSION_MESSAGE, exception);

        if (exception == null)
            throw new NullPointerException(NULL_CAUSE_MESSAGE);

        if (suppressedExceptions == null) // Suppressed exceptions not recorded
            return;

        if (suppressedExceptions == SUPPRESSED_SENTINEL)
            suppressedExceptions = new ArrayList&lt;&gt;(1);

        suppressedExceptions.add(exception);
    }
</code></pre>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/40de5c5b5c560f312c15f1cb182fd64a/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">2017 Linux运维人员必会开源运维工具体系</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/852686e9de2f916fccad5261e21bbfee/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">erase()函数</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程鬼谷子的博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>